resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: di-auth-oidc-provider
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/di-auth-oidc-provider.git
      ignore_paths:
        - ci/pipeline.yaml
      branch: main

  - name: pipeline-src
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/di-auth-oidc-provider.git
      paths:
        - ci/pipeline.yaml
      branch: main

  - name: di-auth-oidc-provider-upload
    type: cf-cli
    icon: cloud-upload
    source:
      api: https://api.london.cloud.service.gov.uk
      username: ((cf-username))
      password: ((cf-password))
      org: gds-digital-identity-authentication
      space: sandbox

jobs:
  - name: update-pipeline
    plan:
      - get: pipeline-src
        trigger: true
      - set_pipeline: di-auth-oidc-provider
        file: pipeline-src/ci/pipeline.yaml

  - name: deploy-lambda
    plan:
      - get: di-auth-oidc-provider
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gradle
              tag: 7.0.0-jdk11
          inputs:
            - name: di-auth-oidc-provider
          outputs:
            - name: lambda-zip
          run:
            path: /bin/bash
            args:
              - -euc
              - |
                cd di-auth-oidc-provider
                gradle --no-daemon :serverless:lambda:buildZip
                cp serverless/lambda/build/distributions/lambda.zip ../lambda-zip/

      - task: terraform-plan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: 0.14.10
          params:
            DEPLOYER_ROLE_ARN: ((deployer-role-arn))
          inputs:
            - name: lambda-zip
            - name: di-auth-oidc-provider
          outputs:
            - name: terraform-plan
          run:
            path: /bin/sh
            args:
              - -euc
              - |
                cd di-auth-oidc-provider/ci/terraform
                terraform init -input=false -backend-config "role_arn=${DEPLOYER_ROLE_ARN}"
                terraform plan \
                  -var 'lambda-zip-file=../../../lambda-zip/lambda.zip' \
                  -var "deployer-role-arn=${DEPLOYER_ROLE_ARN}" \
                  -out=../../../terraform-plan/terraform.plan

      - task: terraform-apply
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: 0.14.10
          params:
            DEPLOYER_ROLE_ARN: ((deployer-role-arn))
          inputs:
            - name: lambda-zip
            - name: di-auth-oidc-provider
            - name: terraform-plan
          run:
            path: /bin/sh
            args:
              - -euc
              - |
                cd di-auth-oidc-provider/ci/terraform
                terraform init -input=false -backend-config "role_arn=${DEPLOYER_ROLE_ARN}"
                terraform apply -auto-approve ../../../terraform-plan/terraform.plan

  - name: deploy-app
    plan:
    - get: di-auth-oidc-provider
      trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: gradle
            tag: 7.0.2-jdk16
        inputs:
          - name: di-auth-oidc-provider
        outputs:
          - name: di-auth-oidc-provider-zip
        run:
          path: /bin/bash
          args:
            - -euc
            - |
              cd di-auth-oidc-provider
              gradle --no-daemon build -x :acceptance-tests:test
              cp build/distributions/di-auth-oidc-provider.zip ../di-auth-oidc-provider-zip/
    - put: di-auth-oidc-provider-upload
      params:
        command: push
        app_name: di-auth-oidc-provider
        manifest: di-auth-oidc-provider/manifest.yml
        path: di-auth-oidc-provider-zip/di-auth-oidc-provider.zip

    - put: di-auth-oidc-provider-upload
      params:
        command: push
        app_name: selenium-firefox
        manifest: di-auth-oidc-provider/manifest.yml

  - name: acceptance-tests
    plan:
      - get: di-auth-oidc-provider
        passed:
          - deploy-app
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gradle
              tag: 7.0.2-jdk16
          inputs:
            - name: di-auth-oidc-provider
          params:
            SELENIUM_URL: https://selenium-firefox.london.cloudapps.digital/wd/hub
            IDP_URL: https://di-auth-oidc-provider.london.cloudapps.digital
            RP_URL: https://di-auth-stub-relying-party.london.cloudapps.digital
          run:
            path: /bin/bash
            args:
              - -euc
              - |
                cd di-auth-oidc-provider
                gradle --no-daemon cucumber